### ISSUE TITLE
Bus feedback doesn't work correctly

### ISSUE THREAD

**Issue by 9734-Jba** [bitfocus/companion-module-vbaudio-voicemeeter#12]
When you select a bus with "Bus Select" action, the feedback is the strip feedback.

Here you can find the line and can replace "selectedStrip" by "selectedBus": https://github.com/bitfocus/companion-module-vbaudio-voicemeeter/blob/54267a581e24198ea0c9060e2d9e88d726fb8bf5/src/feedback.ts#L372C60-L372C73

**Comment by thedist** [comment]
This should now be resolved in the upcoming beta build
