### ISSUE TITLE
Recorder Load track doesn't work

### ISSUE THREAD

**Issue by KLyvers** [bitfocus/companion-module-vbaudio-voicemeeter#13]
**Describe the bug**
Trying to configure a button to load an MP3 file on the recorder for playback. The same file loads directly in the application and plays without issue.

**To Reproduce**
Build local companion to Voicemeeter (not using proxy)
Add button -> Press action -> Voicemeeter: Recorder - Load Track
Provide absolute file path to file, including extension (C:\Users\KLyvers\Documents\Music\song.mp3)
On press of button Voicemeeter shows "undefined" where it would show the file path and "Error: Cannot open File"

Of note: did try adding single and double quotes around the path in the `Filepath` section of button configuration.

**Expected behaviour**
A native streamdeck plugin uses this same path to load file and play

**Screenshots**

**System (please complete the following information):**

- Companion Version: [3.1.2 (3.1.2+6243-stable-05c37a10)](https://bitfocus.io/companion/)
- Voicemeeter Banana 2.0.6.8 

**Additional context**

**Comment by thedist** [comment]
A load track bug was fixed last month, try a newer version of Companion as the one you're on is quite a while back.

**Comment by KLyvers** [comment]
Running the "beta" version of companion has fixed this, Thank you!

**Comment by KLyvers** [comment]
The plugin included with Companion 3.2.0+6647-beta-5aec8e7e does resolve this issue. Thank you!
