### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by JarodShowstream** [bitfocus/companion-module-vbaudio-voicemeeter#19]
Im a rookie when it comes to code and node.js, could you provide a bit more explanation on how to setup to the voicemeter companion module.

I just want to use it to control my local instance of voicemeter, in companion its stuck on Initializing.

Currently using voicmeter macros and Vicreo but want to streamline the process.

**Comment by thedist** [comment]
If Voicemeeter is on the same machine as Companion then you shouldn't need to do anything extra, as running the proxy is only for if the machine running Voicemeeter is separate from Companion.

If Voicemeeter is local to Companion and it's not working, press the `>_` button next to the connection on Companions connections screen to open the logs, and see if there are any messages shown.

**Comment by JarodShowstream** [comment]
appreciate the quick response! I assumed i didnt need the proxy stuff locally so thank you for confirming that as its a bit out of my depth.

Im still getting this error in the logs.

error: (node:9812) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by thedist** [comment]
Those messages should not be an issue that would prevent it from connecting to Voicemeeter. One other thing I can suggest checking is if you look at the Voicemeeter UI and look for the R symbol for remote connections and see if either they're all on (which would prevent new connections, such as from Companion), or if one of the remote connection symbols turns on/off if you enable and disable the Voicemeeter connection in Companion.

![voicemeeter8_3tJpGwIxbJ](https://github.com/bitfocus/companion-module-vbaudio-voicemeeter/assets/12213790/d82fea9a-ce0e-4854-805c-fbd4cefeac5d)

**Comment by JarodShowstream** [comment]
Its actually working now, I guess it just needed more time to initialize. Appreciate your help!
