### ISSUE TITLE
Add macros & custom commands

### ISSUE THREAD

**Issue by nacalai** [bitfocus/companion-module-vbaudio-voicemeeter#20]
It would be very beneficial and a quality of life improvement, if the module could support running **custom api commands**, and also, being able to **trigger a macro button**.

For example, now I want to control VBAN streams, on and off, and there is no action for that in the module it seems. So, being able to call whatever script I wish via a custom command, would be super nice.

![image](https://github.com/bitfocus/companion-module-vbaudio-voicemeeter/assets/4357694/9d617efa-17cc-4a96-85cb-e12501561022)

**Comment by thedist** [comment]
Unfortunately this is taking longer than expected, as while I've now implemented actions for controlling VBAN settings, Macro Buttons, and sending a raw command, there have been changes to the build process that now prevent the Voicemeeter module from correctly building so this may take time some to resolve.

**Comment by nacalai** [comment]
Alright, thanks for the update! Lovely to hear you implementing this regardless.  Please keep me posted :)

**Comment by thedist** [comment]
The latest update to the module, v2.0.0, which is a complete revamp of how the module connects to Voicemeeter does now include the ability to control Macro Buttons, as well as sending raw commands.
