### ISSUE TITLE
Connection crashes as soon as its installed.

### ISSUE THREAD

**Issue by cfarence** [bitfocus/companion-module-vbaudio-voicemeeter#25]
**Describe the bug**
The connection crashes as soon as its installed. I'm currently running companion using the docker container so I expected to need to use the proxy in order to get to voicemeeter. However immediately after clicking install the connection goes into a crash loop. Now settings page to enter connection details is ever presented. I've attached the logs that it puts out, looking over them I don't see anything that stands out though I'm new to companion connection development so I might not be looking in the right place.

**To Reproduce**

Installing the connection, no setup was done yet.

**Expected behaviour**
Connection to run and present the settings page to enter voicemeeter connection details.

**Logs**

Created during the crash.

[module-log-9_18_2024-11_36_48 PM.csv](https://github.com/user-attachments/files/17053192/module-log-9_18_2024-11_36_48.PM.csv)

**System (please complete the following information):**

- Companion Version

Companion 3.4.0 docker container.
ghcr.io/bitfocus/companion/companion:v3.4.0

- Voicemeeter Type and Version

Voicemeeter Potato 3.1.1.3

**Comment by thedist** [comment]
I'm not sure what may be currently causing issue, as It's not something I can reproduce as I don't run Companion in a docker container.

This may be resolved in the upcoming major version change where after working with VBAudio to get some changes made to VBAN in Voicemeeter it'll allow this module to entirely use VBAN for communication, and so work without needing to hook into a DLL, or run proxies, or anything like that and it'll remove some of the dependencies that cause issues on certain machines.

**Comment by thedist** [comment]
The latest update to the module, v2.0.0, will soon be available in the Beta versions of Companion later today, this completely revamps the connection to Voicemeeter and should remove the need for proxies or DLL hooks and instead use VBAN.

There is some minor loss of functionality, and this does require a recent version of Voicemeeter so that VBAN will work correctly, but should resolve a lot of connection issues.
